modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/UnlikePaladin/paladins-furniture/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "pfm"
version = "${version}"
displayName = "Paladin's Furniture"
authors = "UnlikePaladin"
description = '''
A Brand-New Furniture mod for Modern Minecraft where things are functional!
'''
logoFile = "icon.png"
credits = "Translators: lzyzl6, MIHONO, WrenXing"

[[dependencies.pfm]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pfm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.pfm]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.62,)"
ordering = "NONE"
side = "BOTH"